settings:
  wait_time: 15
  progress_bar_done_sprite: ✔
  progress_bar_empty_sprite: ▱
  progress_bar_full_sprite: ▰
package_managers:
  apt: False
  cargo: False
  dnf: False
  flatpak: False
  snapcraft: False
  yum: False
  zypp: False
informations:
  version: 0.1